name: World Notify
description: World Notify
author: aki77
inputs:
  token:
    description: "World token"
    required: true
  participationId:
    description: "Participation id"
  groupId:
    description: "Group id"
  content:
    description: "Comment content"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: node "$GITHUB_ACTION_PATH/notify.mjs"
      env:
        WORLD_TOKEN: ${{ inputs.token }}
        WORLD_PARTICIPATION_ID: ${{ inputs.participationId }}
        WORLD_GROUP_ID: ${{ inputs.groupId }}
        WORLD_CONTENT: ${{ inputs.content }}
