name: notify-test
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          token: ${{ secrets.PRO_WORLD_NOTIFY_APP_TOKEN }}
          participationId: 9406,9406
          content: |
            world-notify-action リリース
